{
  "devices": [
    {
      "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#devices/$entity",
      "id": "00000000-0000-0000-0000-000000000001",
      "accountEnabled": true,
      "approximateLastSignInDateTime": "2020-01-01T00:00:00Z",
      "createdDateTime": "2020-01-01T00:00:00Z",
      "deviceId": "11111111-1111-1111-1111-111111111111",
      "deviceVersion": 2,
      "displayName": "DummyDevice-1",
      "exchangeActiveSyncIds": [],
      "operatingSystem": "Windows",
      "operatingSystemVersion": "10.0.0.0",
      "physicalIds": [
        "[AzureResourceId]:/subscriptions/00000000-0000-0000-0000-000000000001/resourceGroups/DummyResourceGroup/providers/Microsoft.Compute/virtualMachines/DummyDevice-1",
        "[USER-GID]:00000000-0000-0000-0000-000000000001:0000000001",
        "[GID]:g:0000000001",
        "[USER-HWID]:00000000-0000-0000-0000-000000000001:0000000001",
        "[HWID]:h:0000000001"
      ],
      "profileType": "SecureVM",
      "registrationDateTime": "2020-01-01T00:00:00Z",
      "systemLabels": [],
      "trustType": "AzureAd",
      "extensionAttributes": {},
      "alternativeSecurityIds": [
        {
          "type": 2,
          "key": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
        }
      ]
    }
  ]
}
